version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

      - run:
          name: Build
          command: apk add cmocka

      - run:
          name: Build
          command: make -B

      - run:
          name: Memory
          command: make leaktest -B


      - run:
          name: Test
          command: make test -B