version: 2
jobs:
  build:
    docker:
      - image: jonay2000/helios-test:latest

    steps:
      - checkout


      - run:
          name: Build
          command: make -B

      - run:
          name: Test
          command: make test -B